const mongoose = require('mongoose');

const partnerSchema = new mongoose.Schema({
  franchiseId: { type: String, unique: true, required: true },
  instituteName: { type: String, required: true },
  instituteType: { type: String, enum: ['new', 'existing'], default: 'new' },
  centerType: { type: String, default: 'Computer & IT Training' },
  ownerName: { type: String, required: true },
  slug: { type: String, unique: true, required: true, lowercase: true },
  email: { type: String, required: true, lowercase: true },
  phone: { type: String, required: true },
  alternatePhone: { type: String },
  aadhaarNumber: { type: String },
  panNumber: { type: String },
  password: { type: String, select: false },
  address: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  pincode: { type: String },
  landmark: { type: String },
  mapsLink: { type: String },
  premisesType: { type: String, enum: ['owned', 'rented'], default: 'rented' },
  totalArea: { type: Number },
  classrooms: { type: Number, default: 1 },
  computers: { type: Number, default: 0 },
  logo: { type: String },
  tagline: { type: String, default: '' },
  themeColor: { type: String, default: '#2563eb' },
  loginBgImage: { type: String },
  agreementStartDate: { type: Date, required: true },
  agreementEndDate: { type: Date },
  securityDeposit: { type: Number, default: 0 },
  franchiseFee: { type: Number, default: 0 },
  paymentMode: { type: String, enum: ['yearly'], default: 'yearly' },
  bankDetails: {
    accountNumber: { type: String },
    bankName: { type: String },
    ifscCode: { type: String },
  },
  gstNumber: { type: String },
  documents: {
    idProof: { type: String },
    institutePhoto: { type: String },
  },
  references: [{
    name: { type: String },
    phone: { type: String },
    relation: { type: String },
  }],
  status: {
    type: String,
    enum: ['active', 'inactive', 'terminated', 'pending'],
    default: 'active',
  },
  establishedYear: { type: Number },
  socialLinks: {
    facebook: { type: String, default: '' },
    instagram: { type: String, default: '' },
    youtube: { type: String, default: '' },
    whatsapp: { type: String, default: '' },
  },
  description: { type: String, default: '' },
  showInAdmissionForm: { type: Boolean, default: true },
  upiId: { type: String, default: '' },
  paymentQrImage: { type: String, default: '' },
  proposalDetails: { type: mongoose.Schema.Types.Mixed },
  paymentInfo: {
    paymentMode: { type: String, enum: ['online_razorpay', 'offline_pay_later', 'bank_transfer'], default: 'offline_pay_later' },
    paidAmount: { type: Number, default: 0 },
    planName: { type: String },
    planFee: { type: Number, default: 0 },
    paymentStatus: { type: String, enum: ['pending', 'paid', 'failed'], default: 'pending' },
    razorpayOrderId: { type: String },
    razorpayPaymentId: { type: String },
    razorpaySignature: { type: String },
    paidAt: { type: Date },
  },
}, { timestamps: true });

module.exports = mongoose.model('Partner', partnerSchema);
