const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
  partnerId: { type: mongoose.Schema.Types.ObjectId, ref: 'Partner', required: false },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  fullName: { type: String, required: true },
  fatherName: { type: String },
  motherName: { type: String },
  dateOfBirth: { type: Date },
  gender: { type: String, enum: ['male', 'female', 'other'] },
  phone: { type: String, required: true },
  email: { type: String, lowercase: true },
  address: { type: String },
  city: { type: String },
  state: { type: String },
  pincode: { type: String },
  photo: { type: String },
  idProof: { type: String },
  idProofType: { type: String, enum: ['aadhaar', 'pan', 'voter', 'driving_license', 'passport', 'other'] },
  idProofNumber: { type: String },
  qualification: { type: String },
  previousEducation: { type: String },
  guardianName: { type: String },
  guardianPhone: { type: String },
  status: {
    type: String,
    enum: ['active', 'inactive', 'completed', 'dropout'],
    default: 'active',
  },
  enrollmentDate: { type: Date, default: Date.now },
  applicationNo: { type: String, unique: true, sparse: true },
  category: { type: String, enum: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Other'], default: 'General' },
  whatsappPhone: { type: String },
  bloodGroup: { type: String },
  tehsil: { type: String },
  district: { type: String },
  fatherOccupation: { type: String },
  fatherPhone: { type: String },
  familyIncome: { type: String },
  referenceSource: { type: String },
  signature: { type: String },
  tenthDetails: {
    board: String,
    schoolName: String,
    passingYear: String,
    rollNo: String,
    totalMarks: Number,
    obtainedMarks: Number,
    percentage: Number,
    division: String,
  },
  twelfthDetails: {
    board: String,
    stream: String,
    schoolName: String,
    passingYear: String,
    rollNo: String,
    totalMarks: Number,
    obtainedMarks: Number,
    percentage: Number,
    division: String,
  },
  graduationDetails: {
    university: String,
    collegeName: String,
    degree: String,
    stream: String,
    passingYear: String,
    rollNo: String,
    marksType: { type: String, enum: ['percentage', 'cgpa'], default: 'percentage' },
    totalMarks: Number,
    obtainedMarks: Number,
    cgpa: Number,
    percentage: Number,
    division: String,
  },
  declarationsAgreed: { type: Boolean, default: false },
  marksheet: { type: String },
  boardUniversity: { type: String },
  passingYear: { type: String },
  percentage: { type: Number },
  approvalStatus: {
    type: String,
    enum: ['pending', 'approved', 'rejected'],
    default: 'approved',
  },
  courseId: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Course' }],
  batchIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Batch' }],
  projectIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Project' }],
  studentIdNo: { type: String, unique: true, sparse: true },
  dropoutDate: { type: Date },
  dropoutReason: { type: String },
  uploadedDocuments: [{
    docName: { type: String, required: true },
    fileUrl: { type: String, required: true },
    uploadedAt: { type: Date, default: Date.now },
  }],
  paymentInfo: {
    paymentMode: { type: String, enum: ['online_razorpay', 'pay_at_center', 'free'], default: 'pay_at_center' },
    paidAmount: { type: Number, default: 0 },
    paymentStatus: { type: String, enum: ['pending', 'paid', 'failed'], default: 'pending' },
    razorpayOrderId: { type: String },
    razorpayPaymentId: { type: String },
    razorpaySignature: { type: String },
    paidAt: { type: Date },
  },
}, { timestamps: true });

studentSchema.index({ partnerId: 1, phone: 1 });

module.exports = mongoose.model('Student', studentSchema);
